# Generated by Django 5.0.3 on 2024-03-15 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_surveys', '0002_rename_topic_site_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='topic',
            new_name='site',
        ),
    ]
