# Generated by Django 5.0.3 on 2024-03-16 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_surveys', '0005_alter_note_options_alter_site_options_note_publish_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'verbose_name_plural': 'notes'},
        ),
        migrations.AlterModelOptions(
            name='site',
            options={},
        ),
        migrations.RemoveField(
            model_name='note',
            name='publish',
        ),
        migrations.RemoveField(
            model_name='note',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='site',
            name='publish',
        ),
        migrations.RemoveField(
            model_name='site',
            name='updated',
        ),
    ]
