# Generated by Django 5.0.3 on 2024-03-16 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_surveys', '0006_alter_note_options_alter_site_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='site',
            name='slug',
        ),
    ]
